# wrangler.toml for Deploy to Cloudflare button:
# https://developers.cloudflare.com/workers/platform/deploy-buttons/

name = "zurg-serverless"
main = "src/worker.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
preview_urls = false  # Disable versioned preview URLs

[triggers]
crons = ["0 */1 * * *"]  # hourly cron triggers for cache refreshes

[vars]
RD_TOKEN = "JCS3CFDKVVHV5AIPFIBPS6PLLQKF2BUQYJN4SDMXVKZ2B2MVGCKA"
USERNAME = "Frpg"
PASSWORD = "SQUNOM4P7WYRQ"
API_ACCOUNT_ID = "Frpg"  # auto-populated during deployment
REFRESH_INTERVAL_SECONDS = "15"
API_TIMEOUT_SECONDS = "30"
TORRENTS_PAGE_SIZE = "1000"
WORKER_NAME = "zurg-serverless"

[[d1_databases]]
binding = "DB"
database_name = "zurg-serverless-db"
database_id = "de1b6753-77b1-4851-bbd6-f9676e920aec" # auto-populated during deployment
